# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rooter.se
email: johan@rooter.se
description: > # this means to ignore newlines until "baseurl:"
  Homepage for Johan Andersson, a devop student at Linnéuniversitetet. 
  Latest news and projects are posted here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brocahontaz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brocahontaz
github_username:  brocahontaz
lang: en
shortname: brocahontaz
timezone: Europe/Stockholm

authordesc: > # this means to ignore newlines until "markdown:"
  Johan is the founder and creator of Rooter.se - which now acts as the main portal for his news, projects and contact. 
  At the moment, he is studying at Linnéuniversitetet to be a devop. Since before, he has studied quite a lot of object oriented programming, 
  and also self taught a bunch of web developing skills.

# Build settings
markdown: kramdown
theme: 
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock